---
- name: Deploy Nginx with custom configuration
  hosts: web
  become: true
  vars_files:
    - main.yml  # Reference the variables file
  gather_facts: yes

  tasks:
    - name: Ensure apt cache is updated (for Debian-based systems)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx package
      ansible.builtin.package:
        name: "{{ nginx_package_name }}" # Variable for the package name
        state: present
